matrix:
  include:
    - language: go
      go: 1.13.x
      install: true
      script:
        - ./test.sh
      deploy:
        # deploy API
        - provider: heroku
          api_key: $HEROKU_PRODUCTION_API_KEY
          app: $HEROKU_APP_NAME
        

notifications:
  email: false
